server/djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL

    # path for about view
    path(route='about', view=views.about, name='about'),

    # path for contact us view
    path(route='contact', view=views.contact, name='contact'),

    # path for registration
    path(route='registration', view=views.registration_request, name='registration'),

    # path for login
    path(route='login', view=views.login_request, name='login'),

    # path for logout
    path(route='logout', view=views.logout_request, name='logout'),

    # path for dealer reviews view
    path(route='', view=views.get_dealerships, name='index'),

    # path for add a review view

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangoapp/models.py
from django.db import models
from django.utils.timezone import now


# Create your models here.

# <HINT> Create a Car Make model `class CarMake(models.Model)`:
# - Name
# - Description
# - Any other fields you would like to include in car make model
# - __str__ method to print a car make object


# <HINT> Create a Car Model model `class CarModel(models.Model):`:
# - Many-To-One relationship to Car Make model (One Car Make has many Car Models, using ForeignKey field)
# - Name
# - Dealer id, used to refer a dealer created in cloudant database
# - Type (CharField with a choices argument to provide limited choices such as Sedan, SUV, WAGON, etc.)
# - Year (DateField)
# - Any other fields you would like to include in car model
# - __str__ method to print a car make object


# <HINT> Create a plain Python class `CarDealer` to hold dealer data


# <HINT> Create a plain Python class `DealerReview` to hold review data

server/djangoapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
# from .models import related models
# from .restapis import related methods
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from datetime import datetime
import logging
import json

# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create your views here.

# Create an `about` view to render a static about page
def about(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/about.html', context)

# Create a `contact` view to return a static contact page
def contact(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/contact.html', context)

# Create a `login_request` view to handle sign in request
def login_request(request):
    if request.method == "POST":
        username = request.POST['usernameInput']
        password = request.POST['passwordInput']

        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
        
        return redirect("djangoapp:index")
        
# Create a `logout_request` view to handle sign out request
def logout_request(request):
    if request.method == "GET":
        logout(request)
        return redirect("djangoapp:index")

# Create a `registration_request` view to handle sign up request
def registration_request(request):
    context = {}

    # If it is a GET request, just render the registration page
    if request.method == 'GET':
        return render(request, 'djangoapp/registration.html', context)

    # If it is a POST request, then create the user and return to the main page
    elif request.method == 'POST':
        # Get user information from request.POST
        username = request.POST['username']
        password = request.POST['password']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            # Check if user already exists
            User.objects.get(username=username)
            user_exist = True
        except:
            # If not, simply log this is a new user
            logger.debug("{} is new user".format(username))

        # If it is a new user
        if (user_exist == False):
            # Create user in auth_user table
            user = User.objects.create_user(username=username, first_name=first_name, 
                            last_name=last_name, password=password)
            # Login the user and redirect to course list page
            login(request, user)
            return redirect("djangoapp/index.html")
        else:
            # context = {"ErrorMessage":"Username already exists in the system. Please register a different username."}
            return render(request, 'djangoapp/registration.html', context)
    
# ...

# Update the `get_dealerships` view to render the index page with a list of dealerships
def get_dealerships(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/index.html', context)


# Create a `get_dealer_details` view to render the reviews of a dealer
# def get_dealer_details(request, dealer_id):
# ...

# Create a `add_review` view to submit a review
# def add_review(request, dealer_id):
# ...

server/djangoapp/templates/djangoapp/about.html
<html>
<h1>
Welcome to Best Cars dealership, home to the best cars in North America.<br> 
We sell domestic and imported cars at reasonable prices.
</h1>
</html>

server/djangoapp/templates/djangoapp/add_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>

</head>
    <body>
    <!--Add review form here -->
    </body>
</html>

server/djangoapp/templates/djangoapp/contact.html
<html>
<h1>
Welcome to the contact page.
</h1>
</html>

server/djangoapp/templates/djangoapp/dealer_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

    <body>

    <!--Add a nav bar here -->

    <!-- Add reviews as cards -->

    </body>

</html>

server/djangoapp/templates/djangoapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>

</head>

    <body>
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">

            <div class="navbar-header">
                <a class="navbar-brand" href="#">Car Dealership Reviews</a>
                <a class="navbar-brand" href="{% url 'djangoapp:about' %}">About Us</a>
                <a class="navbar-brand" href="{% url 'djangoapp:contact' %}">Contact</a>
            </div>

            {% if user.is_authenticated is False %}
            <form action="{% url 'djangoapp:login' %}"  method="POST">
                {% csrf_token %}
                <input type="text" name="usernameInput" placeholder="username">
                <input type="password" name="passwordInput" placeholder="password">
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
            <form action="{% url 'djangoapp:registration' %}"  method="GET">
                <button type="submit" class="btn btn-light">Sign Up</button>
            </form>
            {% else %}
            <form action="{% url 'djangoapp:logout' %}"  method="GET">
                ({{user.username}})
                <button type="submit" class="btn btn-light">Logout</button>
            </form>

            <!-- <form action="% url 'djangoapp:logout' %" method="GET">
                <button type="submit" class="btn btn-light">Logout</button>
            </form> -->
            {% endif %}

        </div>
        
    </nav> 
        

    <!--Add a dealer table here -->

    </body>

</html>

server/djangoapp/templates/djangoapp/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

    <body>
        <form action="{% url 'djangoapp:registration' %}" method="post">
        <div class="container">
            <h1>Sign Up</h1>
            <hr>
            <label for="username"><b>User Name</b></label><br>
            <input type="text" placeholder="Enter User Name: " name="username" required><br>
            <label for="firstname"><b>First Name</b></label><br>
            <input type="text" placeholder="Enter First Name: " name="firstname" required><br>
            <label for="lastname"><b>Last Name</b></label><br>
            <input type="text" placeholder="Enter Last Name: " name="lastname" required><br>
            <label for="password"><b>Password</b></label><br>
            <input type="password" placeholder="Enter Password: " name="password" required><br>
            <div>
            {% csrf_token %}
            <button class="btn btn-primary" type="submit">Sign Up</button>
            </div>
        </div>
        </form>

    </body>
</html>